modLoader = 'lowcodefml'
loaderVersion = '[45,)'
license = 'MIT'
issueTrackerURL = 'https://github.com/ActuallyBlue/Trims_Overhaul/issues'

[[mods]]
	modId = 'trims_overhaul'
	version = '3.2.3'
	displayName = 'Trims Overhaul'
	description = "Give every trim unique powers, obtainable through quests"
	logoFile = 'pack.png'
	authors = "ActuallyBlue"
	displayURL = 'https://modrinth.com/project/lBHH38D3'